import type { Project } from './types'

const gh = (r: string) => `https://github.com/pankqx/${r}`

// Every claim below comes from the repository's own README/docs (read 2026-10-09) or the résumé.
// "built" = described by the repo as implemented. "planned" = the repo's own roadmap. Nothing else.
export const projects: Project[] = [
  {
    slug: 'eventzee',
    name: 'EventZee',
    kicker: 'Event chaos, filed into a grid, stamped with a QR code.',
    status: 'in-progress',
    statusNote: 'Working student project; the README lists auth, payments and security rules as unfinished.',
    featured: true,
    art: 'eventzee',
    idea: 'Campus events were being registered through spreadsheets. EventZee gives students one place to find events, register, pay and carry a ticket, and gives organisers a live view of who signed up.',
    why: 'Manual registration breaks as soon as people are many and the payment status is in somebody’s head.',
    built: [
      'Two roles in one app: Student and Organiser',
      'Browse, search and filter events by category',
      'Registration flow with a UPI payment screen and an on-device QR e-ticket (ZXing)',
      'Organiser tools: create events, see registrations per event, paid vs pending',
      'Real-time sync through Firestore snapshot listeners',
      'Session persistence with SharedPreferences',
    ],
    planned: [
      'Firebase Authentication',
      'Real payment gateway (Razorpay for UPI suggested)',
      'Per-role Firestore security rules',
      'Tests and CI',
      'Push notifications for registration and payment',
    ],
    stack: ['Kotlin', 'MVVM', 'ViewModel + LiveData', 'Coroutines', 'Firebase Firestore', 'ViewBinding', 'ZXing', 'Gradle'],
    decisions: [
      'MVVM with a single repository and a FirestoreLiveData helper, so screens never talk to Firestore directly.',
      'Tickets are generated on the device — no server is needed to show a QR code.',
    ],
    tradeoffs: [
      'Login is a Firestore query on email and password, and passwords are stored in plain text. The README says plainly this is not production-ready.',
      'Payment is a manual UPI ID; “paid” is a status flag, not a verified transaction.',
      'Firestore rules are open for development. No automated tests yet.',
    ],
    repo: gh('EventZee'),
    evidence: 'EventZee README (features, limitations, roadmap) and résumé.',
  },
  {
    slug: 'paroh',
    name: 'Paroh',
    kicker: 'A quiet desktop room for thinking, where every day is a plain file you own.',
    status: 'in-progress',
    statusNote: 'README: all nine roadmap phases implemented; Phase 8 (opt-in AI) “implemented, in review” as of 2026-10-03.',
    featured: true,
    art: 'paroh',
    idea: 'An offline-first, privacy-first personal operating system with journaling at the centre: writing, habits, to-dos, audio logs, search and reflection in a folder you control.',
    why: 'Journals and “second brains” usually lock your words in someone else’s format. Paroh stores each day as Markdown with YAML frontmatter, readable by any editor.',
    built: [
      'Electron desktop app with a Canvas dashboard and rich-text Editor (Markdown round-trip)',
      'Atomic save pipeline: temp file, read-back validation, fsync, rename',
      'Full-text search (SQLite FTS5) with mood, tag and date filters; wikilinks and backlinks',
      'Habits, to-dos, audio logs, calendar, monthly Chapters, Horizons life timeline',
      'A 24-week healing prompt programme',
      'Ubuntu and Windows package scripts; an Android app path documented',
      'Two opt-in AI features: an Editor’s Note using your own Claude key, and on-device transcription',
      'Tests for vault, frontmatter and domain logic, plus an axe-core accessibility pass',
    ],
    planned: ['See docs/tasks.md in the repo for the live list.'],
    stack: ['Electron', 'React', 'TypeScript', 'Tiptap', 'SQLite FTS5', 'Markdown + YAML', 'Vitest', 'Capacitor'],
    decisions: [
      'One file per day (<vault>/YYYY-MM/YYYY-MM-DD.md). The search index is disposable and rebuilt if corrupt.',
      'Renderer talks to the system only through a typed IPC contract; contextIsolation and sandbox on.',
      'AI is opt-in and never required.',
    ],
    tradeoffs: ['Desktop-first; the phone app is a documented path rather than a store release.'],
    repo: gh('Paroh'),
    evidence: 'Paroh README and docs/tasks.md.',
  },
  {
    slug: 'paroh-twin',
    name: 'Paroh Twin',
    kicker: 'A digital twin that is only allowed to learn what you approve.',
    status: 'experimental',
    statusNote: 'Hackathon build (GATEWAYS 2026, team http dino) with a live demo and labelled sample data.',
    featured: true,
    art: 'twin',
    idea: '“HumanTwin AI”: an explainable model of a student built from what they choose to share. It asks questions aloud, turns answers and journal entries into candidate facts, and waits for approval before learning each one.',
    why: 'Personal AI feels creepy when it learns silently. Here every fact passes a visible consent gate, and every number on the dashboard says where it came from.',
    built: [
      'Twin dashboard with one star per approved fact, weekly load, habit consistency, focus heatmap',
      'Talk: guided questions and a free-talk voice journal (text kept, no audio stored)',
      'Journal and Approvals tray; Memory graph; Ask (what-if simulation); Rhythm, Pulse, Plan',
      'Sources page with per-category consent toggles and a preview of what is sent to the model',
    ],
    planned: ['Connectors for Gmail, WhatsApp, Telegram and Calendar (shown as roadmap, previewed with sample messages)'],
    stack: ['Next.js', 'TypeScript', 'Vercel', 'Hosted model for extraction/conversation with local fallback'],
    decisions: [
      'Consent gate before memory: nothing changes until the student approves a fact.',
      'It is a planning tool, explicitly not a therapy product and not claiming perfect prediction.',
    ],
    tradeoffs: ['Demo data belongs to a labelled sample student; connectors are previews.'],
    repo: gh('paroh-twin'),
    live: 'https://paroh-twin.vercel.app',
    evidence: 'paroh-twin README; GitHub homepage field.',
  },
  {
    slug: 'flow-magic',
    name: 'Flow & Magic',
    kicker: 'A presentation that listens: speech in, visuals out.',
    status: 'concept',
    statusNote: 'Honest status: the GitHub repo contains only a LICENSE. No implementation exists to describe yet.',
    featured: true,
    art: 'flow',
    idea: 'Make presentations more visual and interactive through AI-assisted experiences — an interface between speech, imagination and visual communication.',
    why: 'Slides are static; talks are not.',
    built: [],
    planned: ['Everything. This is an idea waiting for its first commit.'],
    stack: ['TBD'],
    decisions: [],
    tradeoffs: ['Nothing to ship yet — which is exactly why it sits in the lab and not in the trophy room.'],
    repo: gh('flow-magic'),
    evidence: 'Repository tree (LICENSE only) and the brief.',
  },
  {
    slug: 'peece',
    name: 'PEECE',
    kicker: 'A midnight card lounge where every deck is sealed before you bet.',
    status: 'shipped',
    statusNote: 'STATUS.md lists engine, cards, four games, chat, treasury and docs as done; offline “vs the House” mode.',
    featured: true,
    art: 'peece',
    idea: 'A play-money card lounge with four duel games against three AI rivals. The shuffled deck is hashed with SHA-256 and shown before betting; afterwards a Verify button re-hashes it in your browser.',
    why: 'Fairness you can check beats fairness you are told about.',
    built: [
      'Four games: The Omen, Vingt Duel, Liar’s Throne, Three-Card Showdown',
      'Sealed decks with in-browser verification',
      'Double-entry token ledger with a Treasury reconciliation page',
      'Rivals with distinct temperaments and chat',
      'Hand-drawn SVG cards, WebGL burn loader with canvas fallback; no paid assets',
      'Engine tests (31 passing at last status update)',
    ],
    planned: ['Online two-player mode with Supabase', 'Lighthouse pass on the deployed site'],
    stack: ['Vanilla JavaScript', 'Vite', 'SVG', 'WebAudio', 'WebGL', 'SHA-256 (WebCrypto)'],
    decisions: ['Stake is the lower bet; 5% rake on winnings; ties refund; no framework and no image files.'],
    tradeoffs: ['Play money only. Tokens have no cash value.'],
    repo: gh('peece'),
    evidence: 'peece README and STATUS.md.',
  },
  {
    slug: 'brownie-press',
    name: 'The Brownie Press',
    kicker: 'A cart that talks to WhatsApp, because that is where the orders already are.',
    status: 'in-progress',
    statusNote: 'Their own task table: storefront tested; live Supabase project, real content and a real-phone test are still blocked.',
    featured: true,
    art: 'brownie',
    idea: 'Storefront and owner dashboard for a home-based brownie business in Mangalore. Customers build a cart and send one consolidated WhatsApp message.',
    why: 'Nothing is sent automatically and the site never claims an order is accepted — the owner confirms on WhatsApp.',
    built: [
      'Storefront, multi-item cart with validation, WhatsApp checkout and bulk orders',
      'Owner dashboard; Supabase schema with row-level security (tested against an in-memory Postgres)',
      'Three data modes: supabase, demo, unconfigured',
      'Lighthouse mobile 98/100/100/100 on the home page (lab)',
    ],
    planned: ['Live Supabase project, real menu content and photos, domain and SEO'],
    stack: ['React 19', 'TypeScript (strict)', 'Vite', 'Supabase (Auth, Postgres + RLS, Storage)', 'Vitest', 'Playwright'],
    decisions: ['A launch-readiness page blocks go-live while sample data remains.'],
    tradeoffs: ['Menu photos, prices and descriptions are samples. Demo mode has no real security by design.'],
    repo: gh('thebrowniepress'),
    evidence: 'thebrowniepress README and docs/TASKS.md.',
  },
  {
    slug: 'portfolion',
    name: 'portfolion',
    kicker: 'An earlier portfolio, printed like a risograph zine.',
    status: 'experimental',
    statusNote: 'A previous take on this very problem, with a hand-drawn companion named Rhea.',
    featured: false,
    art: 'none',
    idea: 'Four-ink riso aesthetic, ASCII sculptures, and a rooftop chat companion.',
    why: 'A first answer to “what should my portfolio feel like?”',
    built: ['Single content file drives the whole site', 'Companion with local personality and a documented path to a hosted model'],
    planned: ['Cross-device visitor memory (documented swap point)'],
    stack: ['React', 'TypeScript', 'Vite'],
    decisions: [],
    tradeoffs: ['All content values were placeholders in the README.'],
    repo: gh('portfolion'),
    evidence: 'portfolion README.',
  },
  {
    slug: 'leaflet',
    name: 'Leaflet (leavemgm)',
    kicker: 'Leave management with one big button.',
    status: 'shipped',
    statusNote: 'Academic frontend running on mock data; no backend.',
    featured: false,
    art: 'none',
    idea: 'Angular 17 leave-management frontend: apply, history, manager approval queue.',
    why: 'Academic project.',
    built: ['Role-guarded routes', 'Apply / history / manager approval flows on mock services'],
    planned: ['Swap mock services for a MongoDB-backed API'],
    stack: ['Angular 17', 'Signals', 'TypeScript'],
    decisions: [],
    tradeoffs: ['Mock auth accepts any password.'],
    repo: gh('leavemgm'),
    evidence: 'leavemgm README.',
  },
  {
    slug: 'zextractor',
    name: 'zextractor',
    kicker: 'A CLI that finds jewellery shops so a human can call them.',
    status: 'shipped',
    statusNote: 'Python CLI; also used for freelance work per the résumé.',
    featured: false,
    art: 'none',
    idea: 'Search Google Maps for jewellery stores in an area and export name, address and phone to CSV; optional Claude API pitch lines.',
    why: 'Replaces a lost prototype for B2B outreach.',
    built: ['Places API search to CSV', 'Optional --enrich flag using the Claude API'],
    planned: ['De-duplication, resume flag, Google Sheets output'],
    stack: ['Python', 'Google Places API', 'Claude API'],
    decisions: [],
    tradeoffs: ['Places API caps results per query; needs a billed Google key.'],
    repo: gh('zextractor'),
    evidence: 'zextractor README and résumé.',
  },
  {
    slug: 'quizapp',
    name: 'QuizApp',
    kicker: 'Admins write quizzes; students get a score the second they finish.',
    status: 'in-progress',
    statusNote: 'Working; README keeps an honest “things I’m relearning” list.',
    featured: false,
    art: 'none',
    idea: 'ASP.NET Core MVC exam platform with role-based cookie auth and EF Core.',
    why: 'Practice MVC, EF Core and auth end to end.',
    built: ['Admin quiz authoring and analytics table', 'Student attempts with instant scoring and history'],
    planned: ['EF migrations', 'Password hashing', 'Controller tests', 'ASP.NET Identity'],
    stack: ['ASP.NET Core MVC (.NET 8)', 'EF Core + Pomelo', 'MySQL', 'Razor', 'Bootstrap 5'],
    decisions: [],
    tradeoffs: ['Passwords are not hashed with a real algorithm yet (README).'],
    repo: gh('QuizApp'),
    evidence: 'QuizApp README.',
  },
]

export const projectBySlug = (slug: string) => projects.find((p) => p.slug === slug)
