import { chromium } from '/opt/npm-tools/node_modules/playwright/index.mjs'
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1440, height: 850 } })
const errs=[]; p.on('pageerror', e=>errs.push(e.message))
await p.goto('http://localhost:5173/#lab'); await p.waitForTimeout(5200)
await p.screenshot({ path: '/tmp/q_open.png' })
console.log('hash after load:', await p.evaluate(()=>location.hash||'(none)'), 'stage', await p.evaluate(()=>document.body.dataset.stage))
await p.waitForTimeout(3500)
console.log('stage', await p.evaluate(()=>document.body.dataset.stage))
await p.screenshot({ path: '/tmp/q_choice.png' })
await p.evaluate(()=>{}); const btn = p.locator('button').filter({ hasText: /roman/i }).first(); await btn.click().catch(()=>{})
await p.waitForTimeout(2500); console.log('scrollY', await p.evaluate(()=>scrollY))
await p.mouse.move(300,300); await p.mouse.move(700,300,{steps:10}); await p.waitForTimeout(300)
await p.screenshot({ path: '/tmp/q_world.png' })
await p.evaluate(()=>scrollTo(0, 2200)); await p.waitForTimeout(900); await p.mouse.move(400,400,{steps:8})
await p.screenshot({ path: '/tmp/q_ol.png' })
console.log('errs', errs)
await b.close()
